#############################################################################
# Generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#  Jan 18, 2019 03:22:41 PM GMT  platform: Darwin
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} 
    wm focusmodel $top passive
    wm geometry $top 585x493+351+401
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2545 1388
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Add new genome"
    vTcl:DefineAlias "$top" "addIndex" vTcl:Toplevel:WidgetProc "" 1
    entry $top.ent43 \
        -background white -font TkFixedFont -foreground {#000000} \
        -insertbackground black 
    vTcl:DefineAlias "$top.ent43" "fastaEntry" vTcl:WidgetProc "addIndex" 1
    button $top.but44 \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {Open file} 
    vTcl:DefineAlias "$top.but44" "Button1" vTcl:WidgetProc "addIndex" 1
    text $top.tex45 \
        -background white -font TkTextFont -foreground black -height 242 \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -undo 1 \
        -width 526 -wrap word 
    .top42.tex45 configure -font TkTextFont
    .top42.tex45 insert end text
    vTcl:DefineAlias "$top.tex45" "Text1" vTcl:WidgetProc "addIndex" 1
    label $top.lab46 \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -text {Input file} 
    vTcl:DefineAlias "$top.lab46" "Label1" vTcl:WidgetProc "addIndex" 1
    label $top.lab47 \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -text {Genome description} 
    vTcl:DefineAlias "$top.lab47" "Label2" vTcl:WidgetProc "addIndex" 1
    label $top.lab48 \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -text URL 
    vTcl:DefineAlias "$top.lab48" "Label3" vTcl:WidgetProc "addIndex" 1
    entry $top.ent49 \
        -background white -font TkFixedFont -foreground {#000000} \
        -insertbackground black 
    vTcl:DefineAlias "$top.ent49" "Entry2" vTcl:WidgetProc "addIndex" 1
    button $top.but51 \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {Add genome} 
    vTcl:DefineAlias "$top.but51" "Button2" vTcl:WidgetProc "addIndex" 1
    button $top.but52 \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Cancel 
    vTcl:DefineAlias "$top.but52" "Button3" vTcl:WidgetProc "addIndex" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.ent43 \
        -in $top -x 40 -y 40 -width 226 -relwidth 0 -height 30 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but44 \
        -in $top -x 290 -y 40 -anchor nw -bordermode ignore 
    place $top.tex45 \
        -in $top -x 40 -y 120 -width 526 -relwidth 0 -height 242 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab46 \
        -in $top -x 40 -y 20 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 40 -y 100 -width 136 -relwidth 0 -height 18 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 32 -y 380 -width 46 -relwidth 0 -height 18 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent49 \
        -in $top -x 40 -y 400 -width 516 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but51 \
        -in $top -x 460 -y 450 -anchor nw -bordermode ignore 
    place $top.but52 \
        -in $top -x 380 -y 450 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

