#############################################################################
# Generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#  Jan 11, 2019 03:22:16 PM GMT  platform: Darwin
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 842x327+609+943
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2545 1388
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {Input folder} 
    vTcl:DefineAlias "$top.lab45" "Label1" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent46 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent46" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but47 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {Open folder} 
    vTcl:DefineAlias "$top.but47" "Button1" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $top.tCo48 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$top.tCo48" "TCombobox1" vTcl:WidgetProc "Toplevel1" 1
    listbox $top.lis49 \
        -background white -font TkFixedFont -foreground {#000000} -height 154 \
        -highlightcolor black -selectbackground {#c4c4c4} \
        -selectforeground black -width 214 
    .top42.lis49 configure -font TkFixedFont
    .top42.lis49 insert end text
    vTcl:DefineAlias "$top.lis49" "Listbox1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but51 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {Open folder} 
    vTcl:DefineAlias "$top.but51" "Button1_1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but52 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {Open folder} 
    vTcl:DefineAlias "$top.but52" "Button1_2" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $top.tCo53 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$top.tCo53" "TCombobox1_3" vTcl:WidgetProc "Toplevel1" 1
    listbox $top.lis54 \
        -background white -font TkFixedFont -foreground {#000000} -height 154 \
        -highlightcolor black -selectbackground {#c4c4c4} \
        -selectforeground black -width 214 
    .top42.lis54 configure -font TkFixedFont
    .top42.lis54 insert end text
    vTcl:DefineAlias "$top.lis54" "Listbox1_4" vTcl:WidgetProc "Toplevel1" 1
    button $top.but55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {Open folder} 
    vTcl:DefineAlias "$top.but55" "Button1_1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but56 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {Open folder} 
    vTcl:DefineAlias "$top.but56" "Button1_3" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent57 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent57" "Entry1_3" vTcl:WidgetProc "Toplevel1" 1
    button $top.but58 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {Open folder} 
    vTcl:DefineAlias "$top.but58" "Button1_4" vTcl:WidgetProc "Toplevel1" 1
    button $top.but59 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Exit 
    vTcl:DefineAlias "$top.but59" "Button2" vTcl:WidgetProc "Toplevel1" 1
    button $top.but60 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Run 
    vTcl:DefineAlias "$top.but60" "Button2_5" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab61 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {Outpu folder} 
    vTcl:DefineAlias "$top.lab61" "Label2" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab45 \
        -in $top -x 30 -y 20 -anchor nw -bordermode ignore 
    place $top.ent46 \
        -in $top -x 30 -y 40 -width 216 -relwidth 0 -height 30 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 260 -y 40 -width 109 -relwidth 0 -height 28 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tCo48 \
        -in $top -x 27 -y 100 -width 217 -relwidth 0 -height 28 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lis49 \
        -in $top -x 30 -y 140 -width 214 -relwidth 0 -height 154 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but51 \
        -in $top -x 260 -y 140 -width 109 -height 28 -anchor nw \
        -bordermode ignore 
    place $top.but52 \
        -in $top -x 260 -y 180 -width 109 -height 28 -anchor nw \
        -bordermode ignore 
    place $top.tCo53 \
        -in $top -x 440 -y 100 -width 217 -height 28 -anchor nw \
        -bordermode ignore 
    place $top.lis54 \
        -in $top -x 440 -y 145 -width 214 -height 154 -anchor nw \
        -bordermode ignore 
    place $top.but55 \
        -in $top -x 680 -y 150 -width 109 -height 28 -anchor nw \
        -bordermode ignore 
    place $top.but56 \
        -in $top -x 680 -y 190 -width 109 -height 28 -anchor nw \
        -bordermode ignore 
    place $top.ent57 \
        -in $top -x 440 -y 40 -width 216 -height 30 -anchor nw \
        -bordermode ignore 
    place $top.but58 \
        -in $top -x 680 -y 40 -width 109 -height 28 -anchor nw \
        -bordermode ignore 
    place $top.but59 \
        -in $top -x 680 -y 270 -anchor nw -bordermode ignore 
    place $top.but60 \
        -in $top -x 740 -y 270 -width 51 -height 28 -anchor nw \
        -bordermode ignore 
    place $top.lab61 \
        -in $top -x 441 -y 20 -width 80 -height 18 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

