from pathlib import Path
import argparse
import re
import pandas as pd 
import os
import matplotlib.pyplot as plt
import seaborn as sns

# These are the per-position base mismatches generated by diversitools 
# ReadPos	CntRef	CntNonRef	TotalCnt	Freq	AvQual	AvQualRef	AvQualNonRef
# 1	1227205	3193	1230398	0.00259509524560346	0.00189472968875491	0.00182331503907887	0.0293424012060591


parser = argparse.ArgumentParser(description='Plot the mimsamtch frequency as lines for each benchmarked trimming program in a folder.')
parser.add_argument('-d', '--directory', help='the name or path of a directory', required=True)
parser.add_argument('-o', '--output', help='a name for the output lineplot', required=True)
args = parser.parse_args()
#print(args.directory)



data = []
pathlist = Path(args.directory).glob('**/*read.txt')
for path in pathlist:
  # because path is object not string
  path_in_str = str(path)
  filename=os.path.basename(path)
  name1,name2=os.path.splitext(filename)
  print(name1)
  with open(path_in_str) as f:
    next(f)
    for line in f:
      vals = re.split(r'\t+', line)
      if len(name1.split("_", 1))>1:
        name, sample, trimmer, filetype = name1.split("_")
        data.append([name,trimmer,vals[0],vals[4]])


df = pd.DataFrame(data, columns = ['Sample', 'Program', 'Position','MismatchFreq']) 
print(df)
df.Position=pd.to_numeric(df.Position)
df.MismatchFreq=pd.to_numeric(df.MismatchFreq)
df.Program=pd.Categorical(df.Program)
df = df.sort_values(by=['Program','Position'])

g = sns.FacetGrid(df, col="Sample", hue="Program")
g = (g.map(plt.plot, "Position", "MismatchFreq").add_legend())
g.savefig(args.output)

